     20  p__
      3  p__AABM5-125-24
    174  p__Acidobacteriota
   1553  p__Actinobacteriota
      3  p__Aerophobota
      9  p__Altiarchaeota
     19  p__Aquificota
     38  p__Armatimonadota
     21  p__Asgardarchaeota
     12  p__Atribacterota
   1465  p__Bacteroidota
     67  p__Bdellovibrionota
      4  p__Bdellovibrionota_C
      6  p__Bdellovibrionota_E
      5  p__Caldisericota
      3  p__Calditrichota
     10  p__Calescibacterota
    160  p__Campylobacterota
      3  p__CG03
    100  p__Chlamydiota
    364  p__Chloroflexota
      2  p__Chrysiogenota
     16  p__Cloacimonadota
      2  p__Coprothermobacterota
      6  p__CSP1-3
    423  p__Cyanobacteria
      8  p__Deferribacterota
     49  p__Deinococcota
      3  p__Delongbacteria
     29  p__Dependentiae
      4  p__Desantisbacteria
    255  p__Desulfobacterota
     18  p__Desulfobacterota_B
      6  p__Desulfobacterota_C
     12  p__Desulfobacterota_D
      7  p__Desulfobacterota_E
      2  p__Desulfobacterota_G
     71  p__Desulfobacterota_I
      3  p__Dictyoglomota
     19  p__Dormibacterota
      5  p__Eisenbacteria
     52  p__Elusimicrobiota
     10  p__Eremiobacterota
      6  p__Fermentibacterota
     25  p__Fibrobacterota
      2  p__Firestonebacteria
   1556  p__Firmicutes
   1073  p__Firmicutes_A
    100  p__Firmicutes_B
     95  p__Firmicutes_C
     11  p__Firmicutes_D
     13  p__Firmicutes_E
     21  p__Firmicutes_F
     16  p__Firmicutes_G
     39  p__Fusobacteriota
     41  p__Gemmatimonadota
      5  p__Hadarchaeota
    324  p__Halobacteriota
     13  p__Hydrogenedentota
      2  p__Hydrothermarchaeota
      3  p__Iainarchaeota
      3  p__JdFR-76
      2  p__Krumholzibacteriota
      7  p__KSB1
     19  p__Latescibacterota
     35  p__Margulisbacteria
     54  p__Marinisomatota
     55  p__Methanobacteriota
     20  p__Methanobacteriota_A
     50  p__Methanobacteriota_B
     16  p__Methylomirabilota
     11  p__Micrarchaeota
      6  p__Moduliflexota
     61  p__Myxococcota
     12  p__Myxococcota_A
     15  p__Nanoarchaeota
     21  p__Nitrospinota
     78  p__Nitrospirota
      9  p__Nitrospirota_A
      2  p__OLB16
     64  p__Omnitrophota
   1952  p__Patescibacteria
    276  p__Planctomycetota
     11  p__Poribacteria
   3820  p__Proteobacteria
      6  p__Ratteibacteria
      4  p__Riflebacteria
     29  p__SAR324
      7  p__Schekmanbacteria
    173  p__Spirochaetota
      3  p__Sumerlaeota
     35  p__Synergistota
      2  p__SZUA-79
      5  p__TA06
      2  p__Tectomicrobia
    124  p__Thermoplasmatota
    259  p__Thermoproteota
      3  p__Thermosulfidibacterota
     45  p__Thermotogota
     15  p__UBA10199
      3  p__UBP14
    208  p__Verrucomicrobiota
     28  p__WOR-3
     17  p__Zixibacteria
